### ISSUE TITLE
The ragebot is illiterate 

### ISSUE THREAD

**Issue by ImsilverDev** [randroid123123barelybasse/slumpington123#1]
Multiple **illiteracy issues presented by the rag**ebot

**Comment by ImsilverDev** [comment]
![haha](https://github.com/randroid123123barelybasse/slumpington123/assets/44844515/124af838-47a8-4e24-9919-473a481272b8)

**Comment by randroid123123barelybasse** [comment]
sounds like a uid issue to me.
